### ISSUE TITLE
Enforcer Memory Stats File Not Found After Upgrade to 5.2.0

### ISSUE THREAD

**Issue by another-novelty** [neuvector/neuvector#952] opened 2023-08-16 08:18 UTC
**Environment**
Platform: Rancher
Kubernetes version: 1.25.11+rke2r1 (on RKE2)

**Describe the bug**
After the upgrade, our enforcers are constantly generating the following error message:
```
2023-08-03T10:04:47.145|ERRO|AGT|system.(*SystemTools).getMemoryStats: Could not find memory stats file - error=open /host/proc/38729/root/sys/fs/cgroup/memory/memory.stat: no such file or directory filePath=/host/proc/38729/root/sys/fs/cgroup/memory/memory.stat systemtools={bEnable:true info:{Meta:{Version:0.9.2 Timestamp:{wall:13919140360197750914 ext:10046709 loc:0x2fc2400}} Node:{Hostname:neuvector-enforcer-pod-2g2pw MachineID: Hypervisor:vmware Timezone:Europe/Berlin} OS:{Name:SUSE Linux Enterprise Server 15 SP4 Vendor:sles Version:15.4 Release: Architecture:amd64} Kernel:{Release:5.14.21-150400.24.69-default Version:#1 SMP PREEMPT_DYNAMIC Tue Jul 4 13:36:11 UTC 2023 (28b65ec) Architecture:x86_64} Product:{Name:VMware Virtual Platform Vendor:VMware, Inc. Version:None Serial:VMware-### UUID:###} Board:{Name:440BX Desktop Reference Platform Vendor:Intel Corporation Version:None Serial:None AssetTag:} Chassis:{Type:1 Vendor:No Enclosure Version:N/A Serial:None AssetTag:No Asset Tag} BIOS:{Vendor:Phoenix Technologies LTD Version:6.00 Date:11/12/2020} CPU:{Vendor:GenuineIntel Model:Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz Speed:3000 Cache:25344 Cpus:0 Cores:0 Threads:16} Memory:{Type:DRAM Speed:0 Size:65536} Storage:[{Name:sda Driver:sd Vendor:VMware Model:Virtual disk Serial: Size:107}] Network:[{Name:eth0 Driver:vmxnet3 MACAddress:### Port: Speed:0}]} procDir:/host/proc/ cgroupDir:/host/cgroup/ clockTicksPerSecond:100 cgroupVersion:1 cgroupMemoryDir:/sys/fs/cgroup/memory}
```

These messages constantly spam our logging stack with various procs. I already checked the volume mount inside the enforcer pods and in my opinion this is mounted as expected. These issues didn't appear with NeuVector running on version 5.1.3

**To Reproduce**
1. Install neuvector through helm with version 5.1.3
2. Upgrade version through helm to 5.2.0
3. See the enforcers spam the aforementioned error.

**Expected behavior**
No error

**Additional context**
We use neuvector through neuvector-helm and already reported it there: https://github.com/neuvector/neuvector-helm/issues/294

``` sh
/ # hostname
neuvector-enforcer-pod-2g2pw
/ # ls -l /host/proc/
total 0
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 1
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 10
dr-xr-xr-x    9 80       www-data         0 Aug  4 06:42 100034
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 1006
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 1007
dr-xr-xr-x    9 root     root             0 Aug  4 06:55 10086
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 101
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 1012
dr-xr-xr-x    9 root     root             0 Aug  4 06:42 101279
dr-xr-xr-x    9 root     root             0 Aug  1 01:54 10179
dr-xr-xr-x    9 65535    65535            0 Aug  1 01:54 10198
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 102
dr-xr-xr-x    9 root     root             0 Aug  1 01:54 10217
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 1024
dr-xr-xr-x    9 65535    65535            0 Aug  1 01:54 10250
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 103
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 1036
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 104
dr-xr-xr-x    9 root     root             0 Aug  1 01:54 10421
dr-xr-xr-x    9 65535    65535            0 Aug  1 01:54 10441
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 105
dr-xr-xr-x    9 root     root             0 Aug  1 01:54 10513
dr-xr-xr-x    9 65535    65535            0 Aug  1 01:54 10533
dr-xr-xr-x    9 185      root             0 Aug  1 01:54 10615
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 107
dr-xr-xr-x    9 root     root             0 Aug  4 06:44 108409
dr-xr-xr-x    9 root     root             0 Aug  1 01:50 11
dr-xr-xr-x    9 root     root             0 Aug  1 01:54 11107
dr-xr-xr-x    9 65535    65535            0 Aug  1 01:54 11131
/ # ls -l /host/proc/2661/root/sys/fs/
total 0
dr-xr-xr-x    2 root     root             0 Aug  1 02:00 bpf
dr-xr-xr-x    2 root     root             0 Aug  1 02:00 cgroup
drwxr-xr-x    4 root     root             0 Aug  1 02:00 ext4
drwxr-xr-x    3 root     root             0 Aug  1 02:00 fuse
drwxr-xr-x    3 root     root             0 Aug  1 03:00 nfs
dr-xr-xr-x    2 root     root             0 Aug  1 02:00 pstore
/ # ls -l /host/proc/2661/root/sys/fs/cgroup/
total 0
/ #
```

But its also empty on the node itself:
``` sh
worker-03:~ # ll /proc/2661/root/sys/fs/
total 0
dr-xr-xr-x 2 root root 0 Aug  1 04:00 bpf
dr-xr-xr-x 2 root root 0 Aug  1 04:00 cgroup
drwxr-xr-x 4 root root 0 Aug  1 04:00 ext4
drwxr-xr-x 3 root root 0 Aug  1 04:00 fuse
drwxr-xr-x 3 root root 0 Aug  1 05:00 nfs
dr-xr-xr-x 2 root root 0 Aug  1 04:00 pstore
worker-03:~ # ll /proc/2661/root/sys/fs/cgroup/
total 0
```

**Comment by another-novelty** [comment] 2023-08-16 08:19
We assume that [this PR](https://github.com/neuvector/neuvector/pull/949) will fix this issue.

**Comment by 0Styless** [comment] 2023-08-22 14:25
@jaimeyu-suse can you confirm that this PR will fix the issue?

**Comment by jaimeyu-suse** [comment] 2023-08-22 16:30
Not knowing your exact setup (I would have to hop on to verify) but lets see if you can do it on your side.

> The error happens because `worker-03:~ # ll /proc/2661/root/sys/fs/cgroup` isn't found or empty.

To verify on your box, you can try the following without leaking your env to me.

1. Get the memory cgroup path from `/host/proc/2661/cgroups`
2. It will be something like `0::/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod8d76350b_aad8_467d_99fd_c6ec2e0b15a6.slice/cri-containerd-c95d16aa748237e6c9dcc6c40f9dc77b66b75d5a4807578d000e0b3683490dd4.scope`
3. So now go check if `/host/cgroup` and look for `kubepods.slice`. This directory should be full and the path in the above cgroup file will be in this directory. Something like `/host/cgroup/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod8d76350b_aad8_467d_99fd_c6ec2e0b15a6.slice/cri-containerd-c95d16aa748237e6c9dcc6c40f9dc77b66b75d5a4807578d000e0b3683490dd4.scope` Note that this is for cgroup v2, in cgroup v1 you will need add the subsystem so example it would be `/host/cgroup/memory` and then try the path. 
4. We're also looking at using `/proc/1/root/proc/2661/root/sys/fs/cgroup` << and the files should be in here. 

A hint, when you're in the cgroup directory, you can double check you're in the right namespace by `cat cgroup.procs`. This will dump out all the processes in this namespace.

**Comment by 0Styless** [comment] 2023-08-23 06:05
At first, I looked for example proc in the recent logs of the enforcer:

```bash
 neuvector-enforcer-pod-85hh7 neuvector-enforcer-pod 2023-08-23T05:48:23.314|ERRO|AGT|system.(*SystemTools).getMemoryStats: Could not find memory stats file - error=open /host/proc/30686/root/sys/fs/cgroup/memory/memory.stat: no such file or directory filePath=/host/proc/30686/root/sys/fs/cgroup/memory/memory.stat systemtools={bEnable:true info:{Meta:{Version:0.9.2 Timestamp:{wall:13919297825380814825 ext:9400934 loc:0x2fc2400}} Node:{Hostname:neuvector-enforcer-pod-85hh7 MachineID: Hypervisor:vmware Timezone:Europe/Berlin} OS:{Name:SUSE Linux Enterprise Server 15 SP4 Vendor:sles Version:15.4 Release: Architecture:amd64} Kernel:{Release:5.14.21-150400.24.69-default Version:#1 SMP PREEMPT_DYNAMIC Tue Jul 4 13:36:11 UTC 2023 (28b65ec) Architecture:x86_64} Product:{Name:VMware Virtual Platform Vendor:VMware, Inc. Version:None Serial:VMware-} Board:{Name:440BX Desktop Reference Platform Vendor:Intel Corporation Version:None Serial:None AssetTag:} Chassis:{Type:1 Vendor:No Enclosure Version:N/A Serial:None AssetTag:No Asset Tag} BIOS:{Vendor:Phoenix Technologies LTD Version:6.00 Date:11/12/2020} CPU:{Vendor:GenuineIntel Model:Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz Speed:3000 Cache:25344 Cpus:0 Cores:0 Threads:16} Memory:{Type:DRAM Speed:0 Size:65536} Storage:[{Name:sda Driver:sd Vendor:VMware Model:Virtual disk Serial: Size:107}] Network:[{Name:eth0 Driver:vmxnet3 MACAddress: Port: Speed:0}]} procDir:/host/proc/ cgroupDir:/host/cgroup/ clockTicksPerSecond:100 cgroupVersion:1 cgroupMemoryDir:/sys/fs/cgroup/memory}
```

1. Searched for the cgroup path:

```bash
cat /proc/30686/cgroup

13:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
12:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
11:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
10:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
9:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
8:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
7:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
6:misc:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
5:rdma:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
4:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
3:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
2:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
```

2. Checked for the mentioned paths

Seems on **SUSE Linux Enterprise 15** the memory.stat file is in this path:

```bash
ll /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4137cf_a7e9_4809_9863_8ed7912ee696.slice/

-rw-r--r-- 1 root root 0 Aug  1 03:54 cgroup.clone_children
--w--w--w- 1 root root 0 Aug  1 03:54 cgroup.event_control
-rw-r--r-- 1 root root 0 Aug  1 03:54 cgroup.procs
drwxr-xr-x 2 root root 0 Aug  1 03:55 cri-containerd-441814750de07ce7c9cc4e38233c396d4ea2bbd43120964513f0dff9c0bf35d7.scope
drwxr-xr-x 2 root root 0 Aug  1 03:54 cri-containerd-c243c86ff67e8d980d0bd6e4bb83c1d9f8109e67b0870fff4e6a6cddd439edbe.scope
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.failcnt
--w------- 1 root root 0 Aug  1 03:54 memory.force_empty
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.failcnt
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.limit_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.max_usage_in_bytes
-r--r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.slabinfo
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.tcp.failcnt
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.tcp.limit_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.tcp.max_usage_in_bytes
-r--r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.tcp.usage_in_bytes
-r--r--r-- 1 root root 0 Aug  1 03:54 memory.kmem.usage_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.limit_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.max_usage_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.memsw.failcnt
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.memsw.limit_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.memsw.max_usage_in_bytes
-r--r--r-- 1 root root 0 Aug  1 03:54 memory.memsw.usage_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.move_charge_at_immigrate
-r--r--r-- 1 root root 0 Aug  1 03:54 memory.numa_stat
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.oom_control
---------- 1 root root 0 Aug  1 03:54 memory.pressure_level
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.soft_limit_in_bytes
-r--r--r-- 1 root root 0 Aug  1 03:54 memory.stat
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.swappiness
-r--r--r-- 1 root root 0 Aug  1 03:54 memory.usage_in_bytes
-rw-r--r-- 1 root root 0 Aug  1 03:54 memory.use_hierarchy
-rw-r--r-- 1 root root 0 Aug  1 03:54 notify_on_release
-rw-r--r-- 1 root root 0 Aug  1 03:54 tasks
```

So if I'm getting your last message right, you are not searching in this path?

**Comment by 0Styless** [comment] 2023-08-24 07:04
So I double-checked this inside the pod:

```bash
/ # cat /host/proc/15028/cgroup
13:cpuset:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
12:freezer:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
11:misc:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
10:memory:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
9:pids:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
8:hugetlb:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
7:perf_event:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
6:cpu,cpuacct:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
5:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
4:net_cls,net_prio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
3:devices:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
2:rdma:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
1:name=systemd:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
0::/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope
```

`cgroup.procs` file is empty:

```bash
/ # cat /host/cgroup/memory/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope/cgroup.procs
```

But `memory.stat` is there:

```bash
/ # cat /host/cgroup/memory/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd22374cb_ab58_49f5_bff4_c864001eba28.slice/cri-containerd-40f3b4ff008f60405372a5daaab811e8aabb5972c36cd76721786289773128f8.scope/memory.stat
cache 4096
rss 40960
rss_huge 0
shmem 0
mapped_file 0
dirty 0
writeback 0
swap 0
pgpgin 573
pgpgout 562
pgfault 1039
pgmajfault 0
inactive_anon 36864
active_anon 4096
inactive_file 0
active_file 4096
unevictable 0
hierarchical_memory_limit 67346948096
hierarchical_memsw_limit 9223372036854771712
total_cache 4096
total_rss 40960
total_rss_huge 0
total_shmem 0
total_mapped_file 0
total_dirty 0
total_writeback 0
total_swap 0
total_pgpgin 573
total_pgpgout 562
total_pgfault 1039
total_pgmajfault 0
total_inactive_anon 36864
total_active_anon 4096
total_inactive_file 0
total_active_file 4096
total_unevictable 0
```

controller-deployment is also correct in my opinion:

```yaml
...
        volumeMounts:
        - mountPath: /var/neuvector
          name: nv-share
        - mountPath: /var/run/containerd/containerd.sock
          name: runtime-sock
          readOnly: true
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/cgroup
          name: cgroup-vol
          readOnly: true
        - mountPath: /etc/config
          name: config-volume
          readOnly: true
      volumes:
      - name: nv-share
        persistentVolumeClaim:
          claimName: neuvector-persistent-data
      - hostPath:
          path: /run/k3s/containerd/containerd.sock
          type: ""
        name: runtime-sock
      - hostPath:
          path: /proc
          type: ""
        name: proc-vol
      - hostPath:
          path: /sys/fs/cgroup
          type: ""
        name: cgroup-vol
      - name: config-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: neuvector-init
              optional: true
          - secret:
              name: neuvector-init
              optional: true
```

So, is there anything else we can do except waiting for the PR to get merged?

**Comment by jaimeyu-suse** [comment] 2023-08-24 07:35
@0Styless Unfortunately no, you would have to wait.

I've actually haven't seen an empty `cgroup.procs` before. I guess its technically possible but not sure what it means in your situation. Maybe the proc left the cgroup by that point? But we're not checking that file, it was just something I used while debugging and verifying my paths. 

> The cgroup.procs file can be read to obtain a list of the
>        processes that are members of a cgroup.  The returned list of
>        PIDs is not guaranteed to be in order.  Nor is it guaranteed to
>        be free of duplicates.  (For example, a PID may be recycled while
>        reading from the list.) - https://man7.org/linux/man-pages/man7/cgroups.7.html

**Comment by 0Styless** [comment] 2023-08-24 08:37
Is there a time plan when the PR will be merged, or when there will be a new release with fix?

At the moment, this is a huge blocker because the log messages overloading our entire logging stack.

**Comment by jaimeyu-suse** [comment] 2023-08-24 16:11
Unfortunately no, you would have to contact your rep for release information. As soon as I can is my goal but I can't really comment on releases since that is above my pay grade. 

And I fully understand your pain, that is one of the goals is to reduce the logging even when errors do occur to help you out.

**Comment by 0Styless** [comment] 2023-08-25 05:55
Or at least any workaround? Because we don't see this issue with NeuVector version 5.1.3.

**Comment by jaimeyu-suse** [comment] 2023-08-25 20:06
Unfortunately I am unaware of any.

**Comment by jaimeyu-suse** [comment] 2023-09-13 19:46
The PR has been merged. Please close once you confirm it in the next release, I believe it will be in 5.2.2 but I have not seen the release notes yet.

**Comment by jilleJr** [comment] 2023-10-06 16:18
Confirmed that v5.2.2 fixed the issue for us

**Comment by 0Styless** [comment] 2023-10-09 08:21
I also confirm that with v5.2.2 this is fixed.

**Closed** 2023-10-09 08:26 UTC

**Comment by jaimeyu-suse** [comment] 2023-10-10 16:40
Glad to hear it. Gave a great day!
