### ISSUE TITLE
docker build not possible 

### ISSUE THREAD

**Issue by haarchri** [neuvector/neuvector#32] opened 2022-01-19 08:56 UTC
docker build is not possible - in code we see a lot of internal ips like `10.1.127.12:5000` 

https://github.com/neuvector/neuvector/search?q=10.1.127.12
https://github.com/neuvector/neuvector/blob/main/Makefile#L3_L4
https://github.com/neuvector/neuvector/blob/main/build/Dockerfile.all#L2
https://github.com/neuvector/neuvector/blob/main/build/Dockerfile.controller#L2
https://github.com/neuvector/neuvector/blob/main/build/Dockerfile.ctrlenf#L1

**Comment by garyduan** [comment] 2022-01-19 19:13
Self build is not supported yet and will be supported in the future. Using #24 to follow up the issue.

**Comment by garyduan** [comment] 2022-01-19 19:14
Duplicate of #24

**Closed** 2022-01-19 20:55 UTC
