### ISSUE TITLE
Hard-coded location for components

### ISSUE THREAD

**Issue by aplanas** [neuvector/neuvector#26] opened 2022-01-18 15:35 UTC
In the code there is hard-coded the location of some binary utilities, mostly expected in `/usr/local/bin`.

**Comment by becitsthere** [comment] 2022-01-20 17:35
Duplicate to #24

**Comment by becitsthere** [comment] 2022-01-20 17:35
Duplicate of #24

**Comment by garyduan** [comment] 2022-01-20 17:37
Ok. I will close this issue and use #24 to track it.

**Closed by garyduan** 2022-01-20 17:37 UTC

**Comment by aplanas** [comment] 2022-01-20 18:34
No, is not duplicated.

As commented, in the code (for example https://github.com/neuvector/neuvector/blob/main/monitor/monitor.c#L102) there are locations in the file system that are hardcoded, pointing in `/usr/local/bin`.  This can be a problem when, lets say, we want to build a package for it (rpm, deb, or for other distributions)
